language: node_js
node_js:
- node
deploy:
  provider: npm
  email: 576303283@qq.com
  api_key:
    secure: UkbfIRoJ3JCvSb7+BAmTzRvdZB0KQ0RBJj1lCs6z1gPK/pxkmeaog97D5CxImon071iT1Wc9OW86mMihcIENy3sBG1pFnbkBBuMXj5GYIgS0Fmo6WpyM6QFZX3sJ9TTfxXfw6RyliSL49ZI3U0b7cYyeLHkRRd55jAzz3ekW4/D1IVFwhkLMABFWZ1c1FTcTOnUy6p2QmHEiEKK0AdnhXdOSnRS9rMqu6QsgZpLOoIFzZxSTn+YUAPnwt8XcqxYZJvIr4sYZ7tkr70HcxCIPO064Px169y0O6T2N3S1GAdTQ9SwI6bMS86im5cNP5uf/nwxuQfwORa+LM/YV7uNUuxCunQshkNzPfVB2GBUWEywKUSBLDKmzKIbg8SOpGrTx9cL8K8Qlyq3oEbKS/594A1oIY4ztOhIZDbY0VDBnoNRcUgfW50KGIlFCt+MOkR+U+axP5muhC2z2ujmi/McSUfziITRkNTdXvVnslq9rhKbSmyw56uVkYGiPPlMN1Xuc81xe4mXwls8ixQGMXcSPTw8SszkmGJF4SXzmbvG+naQ4oMJ6F2eJbPeoQFJSz5S57TtmjXagkQeWVGFFLaXo3pzWXtJs4B64zyCGJ/9U2gPRhq1iEgnHEG9vBEk4y92mnsDcqwVBUhgtYIUY5xnHgTSQHfMFF/jg5G9MqxAWjaQ=
  skip_cleanup: 'true'