language: node_js
node_js:
- node
deploy:
  provider: npm
  email: 576303283@qq.com
  api_key:
    secure: fUuw6Zs/dglDyvGe09M1+KDrLDuuyYZCKWXqxJSEVwoGj4C9GF6ksmEisqzorHWqfY4i6HQlbsP4xaWGR1eGRVQDWHQphFk8Gpr4+ALVfowB7TwdV8W5OZnGq2AKJSSRgMQ7JKAd/RbIgvDyuSeKuQ67dVKxL0CsidgIcxXAvhhaHqWKz+j8WIfP4AlvaiODKbydNBqrWP7qg8gwpbmHpQDUTd5cj78k/HsUiBZu2xPVANJljHEkTd0EMzQVji5K80CeVOxBQPu/k5R22cF8M3z3iSaIQS6BOl4MgV+8i6TJxP9HsMkoG8X++0G+TyE4jfM3iai/WZzkGCt6kn48PMGn3xVrQkXmHRO2zauBKpQIubQ6fNlNYKu5lRuWHGnF8FHoqDmUdEYFArPu5eMlzfn1cSMH4cWVbOj+k2jTcrD7uy5kK1pl4chsCMsOiU7PLcWJzH7muGo7xwx+ypUWc5P+idIi+VEdNzUh5TFoTRr0YXhrg7J5WmMuzgGyUphNWJdyAx1XeYJks8Vk8W1JQ12C2kKnacFlzyadhUQIvFKa8U9IhmO7XZirtFJ0AJecFUBV1SoylP1kjahkdXhuG0f8VOv+DoxeaLCdb1J+om7v90t+dELqaUrU0V/R9QbAj/xPG7ZjH9TorioollDsohqVFd14MdTShk02lFpBZo0=
    repo: paxiong-cc/vue-component
  skip_cleanup: 'true'