language: node_js
node_js:
- node
deploy:
  provider: npm
  email: 576303283@qq.com
  api_key:
    secure: aFP9/VxWxwVSZRhcxNa+dixG7Qc92xC6+DX8Q+VlSL7NoCevbSBP7wkF4SV/7xM0QC1EjAeI19VwibJaAwNKUsD83sUF0hZMQsFZSFgD/KI0886uz7KUWowAm9kpNuEQMF7vMCTBb9SAKiLjSLz52ZuHOSmEK8EmflnV5vE431UgIgx1p4991KVZnBJo/n6YvI5LiUcNs1zLL2SnOQlT8VCf4jyuXkxmjqPcq3CJ6inH1oiY3NphWm4J2wngPZyhjma1LPRzJ7GvlfV/9L7nQMQjYL+gpPiStUe2aCAsGlpyLlf218rF+S47vzzTg0x5dZwk+96ZlmdGAp7+Lj10yxyj9xO8q/ReCu0whtER9akYMs3EvKyt4S0BOLxUqvm8MvDnOdcnvYl+VlxxCqVpAKlEKJuPvaQUJ5YAAiNGyTeDHlcOONF2qD54MgA+Z1j1pUw5V+p2oe8Rwl6tBUQw1U8apBufGh1/sHj/wmmVBnSQ2x0hvRXPvy1nQkLymJxKpDCT8PlhCpRKiVnJDpWj18pud9zYbuB8Q1YZdebcAyw8het7k4nt4bLuImt4vIyKgeAmaaiJ2z6FspViEXhU3XibZH6i+BqNozf6xTVHoQYjNqEVzgY02PD4NQQPjRzUhPpoA9o5CNqdUvzJrX2y02pbOueQtWZeVupQj3wgHfE=
  on:
    tags: true
    repo: paxiong-cc/vue-component
  skip_cleanup: true